version: "3.9"
name: students
services:
  web:
    container_name: next
    build:
      context: next
      dockerfile: Dockerfile-dev
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /next
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - DATABASE_URL={DATABASE_URL}
    depends_on: # make sure db completes set up before running app
      db:
        condition: service_healthy
  db:
    container_name: db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres_user -d t3-db -h db" ]
      interval: 10s # retry after the database is ready
      timeout: 5s
      retries: 5

volumes:
  pgdata: { }



# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
#networks:
#  students:
#    external: true