version: "3.9"
name: scholar
services:
  web:
    container_name: next
    build:
      context: next
      dockerfile: Dockerfile-dev
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /next
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on: # make sure db completes set up before running app
      db:
        condition: service_healthy

  db:
    container_name: db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "scholar"]
      interval: 10s # retry after the database is ready
      timeout: 5s
      retries: 5

  bot:
    container_name: bot
    build:
      context: bot
volumes:
  db-data:



# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
#networks:
#  students:
#    external: true