version: "3.9"
name: scholar

services:
  web:
    build:
      context: .
      target: dev
    command: npm run dev
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    restart: always
    depends_on: # make sure db completes set up before running app
      db:
        condition: service_healthy
    networks:
      - net

  db:
    container_name: db
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "scholar"]
      interval: 10s # retry after the database is ready
      timeout: 5s
      retries: 5
    networks:
      - net

  bot:
    container_name: bot
    build:
      context: bot

volumes:
  db-data:

networks:
  net:



# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
#networks:
#  students:
#    external: true